# Generated by Django 2.2.24 on 2025-03-08 16:30

from django.db import migrations


def is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20250308_2118'),
    ]

    operations = [
        migrations.RunPython(is_new_building),
    ]
