# Generated by Django 5.1.7 on 2025-03-09 10:23

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='RU', verbose_name='номер телефона'),
        ),
    ]
