# Generated by Django 5.1.7 on 2025-03-09 12:55
from tabnanny import check

from django.db import migrations, models


def transfer_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, create = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owner_pure_phone

        )
        owner.flats.set([flat])

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_complaint_flat_alter_complaint_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(verbose_name='ФИО владельца',max_length=200,null=False,db_index=True)
        ),

        migrations.RunPython(transfer_owners),
    ]
